{% set name = "pyexcel-webio" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 039538f1b35351f1632891dde29ef4d7fba744e217678ebb5a501336e28ca265

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyexcel >=0.5.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyexcel_webio

about:
  home: https://github.com/pyexcel-webwares/pyexcel-webio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A generic request and response interface for pyexcel web extensions
  dev_url: https://github.com/pyexcel-webwares/pyexcel-webio

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
